[dev]
    command = "next dev -p 7007"
    targetPort = 7007


[[headers]]
    for = "/*"
    [headers.values]
        Cache-Control = "public, max-age=31536000"
        X-Frame-Options = "DENY"
        X-XSS-Protection = "1; mode=block"

[[headers]]
    for = "/manifest.webmanifest"
    [headers.values]
        Content-Type = "application/manifest+json"