[[headers]]
    for = "/*"
    [headers.values]
        Cache-Control = "public, max-age=31536000"
        X-Frame-Options = "DENY"
        X-XSS-Protection = "1; mode=block"

[[headers]]
    for = "/manifest.webmanifest"
    [headers.values]
        Content-Type = "application/manifest+json"


[[redirects]]
    from = '/api/*'
    to = '/.netlify/functions/:splat'
    status = 200